const defaults = {
  maxTitleWidth: 9,
  maxTitleLines: 4,
  volumeStep: 10,
  seekStep: 10,
  playlistName: "",
  startPlayback: true,
  shufflePlaylist: false,
  sortByAlbum: false,
  playlistPosition: "Clear",
  useCurrentTrack: true,
  trackTitle: "",
  album: "",
  artist: "",
}
